CREATE TABLE IF NOT EXISTS Users (
    id VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    points INTEGER DEFAULT 100,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Books (
    id VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    writer VARCHAR(255) NOT NULL,
    cover_image VARCHAR(255) NOT NULL,
    point INTEGER NOT NULL,
    tags VARCHAR(255) [] NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Orders (
    id VARCHAR(255) UNIQUE NOT NULL,
    user_id VARCHAR(255) REFERENCES Users(id),
    book_id VARCHAR(255) REFERENCES Books(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);